=== MaxNe/wba2/Phase1/src/aufgabe3dXML-Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	
	<xs:simpleType name="Einheitentyp">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Gramm" />
			<xs:enumeration value="Kilogramm" />
			<xs:enumeration value="Teeloeffel" />
			<xs:enumeration value="Essloeffel" />
			<xs:enumeration value="Tasse" />
			<xs:enumeration value="Milliliter" />
			<xs:enumeration value="Liter" />
			<xs:enumeration value="Zeniliter" />
			<xs:enumeration value="Packung(en)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Zutatentyp">
		<xs:attribute name="Name" type="xs:string" />
		<xs:attribute name="Anzahl" type="xs:string" />
		<xs:attribute name="Einheit" type="Einheitentyp" />	
	</xs:complexType>
	
	<xs:element name="Zubereitung">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Schritt" type="xs:string" minOccurs="1" maxOccurs="unbounded" /> 
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="Schwierigkeitsgrad">
		<xs:restriction base="xs:string">
			<xs:pattern value="einfach|normal|schwer" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="Schwierigkeit">
 		<xs:complexType>
			<xs:attribute name="level" type="Schwierigkeitsgrad" /> 			
		</xs:complexType> 
	</xs:element>
	
	<xs:simpleType name="Zeittyp">
		<xs:restriction base="xs:string">
			<xs:pattern value="Minuten|Stunden" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="Zeit">
		<xs:complexType>
			<xs:attribute name="Anzahl" type="xs:string" />
			<xs:attribute name="Einheit" type="Zeittyp" />
		</xs:complexType> 
	</xs:element>
	
	<xs:element name="Brennwert">
		<xs:complexType>
			<xs:attribute name="Kalorien" type="xs:nonNegativeInteger" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Rezept">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Titel" type="xs:string" />
				<xs:element name="Untertitel" type="xs:string" minOccurs="0" />
				<xs:element name="Zutat" type="Zutatentyp" minOccurs="1" maxOccurs="unbounded" />
				<xs:element name="Zubereitung" />
				<xs:element name="Zeit" />
				<xs:element name="Schwierigkeit" />
				<xs:element name="Brennwert" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="Rezeptliste">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Rezept" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== MaxNe/wba2/Phase1/bin/aufgabe3a.xml
<?xml version="1.0"?>
<Rezeptliste
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="aufgabe3dXML-Schema.xsd">


<Rezept>
<Titel>
Lenchen's Schokoladenkuchen
</Titel>
<Zutat Name="Butter" Anzahl="200" Einheit="Gramm"/>
<Zutat Name="Zucker" Anzahl="200" Einheit="Gramm"/>
<Zutat Name="Schokolade, Blockschokolade" Anzahl="200" Einheit="Gramm"/>
<!-- ref="http://www.chefkoch.de/magazin/artikel/105,0/Chefkoch/Schokolade.html" -->
<Zutat Name="Mehl" Anzahl="120" Einheit="Gramm"/>
<Zutat Name="Backpulver" Anzahl="0.5" Einheit="Teeloeffel"/>
<Zutat Name="Vanillezucker" Anzahl="1" Einheit="Packung"/>
<Zutat Name="Ei(er)" Anzahl="4"/>
<Zubereitung>
<Schritt>
Butter und Schokolade im Wasserbad schmelzen.
</Schritt>
<Schritt>
Eier trennen.
</Schritt>
<Schritt>
Eiweiß steif schlagen.
</Schritt>
<Schritt>
Eigelbe, Zucker und Vanillezucker verrühren.
</Schritt>
<Schritt>
Geschmolzene Butter-Schokomasse hinzufügen und mischen.
</Schritt>
<Schritt>
Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.
</Schritt>
<Schritt>
In eine gut gefettete Form geben.
</Schritt>
<Schritt>
Bei 180°Grad 40 – 50 Minuten backen.
</Schritt>
</Zubereitung>
<Zeit Anzahl="1" Einheit="Stunden"/>
<Schwierigkeit level="normal"/>
<Brennwert Kalorien="295"/>
</Rezept>
</Rezeptliste>
